require('dotenv').config()
const pool = require('./db')

const products = [
  { id:'1', slug:'collier-or-saint-louis', name_fr:'Collier en Or de Saint-Louis', name_en:'Saint-Louis Gold Necklace', category:'artisanat', producer:'atelier-toure', price:45000, original_price:null, description_fr:"Collier en or 18 carats serti de perles de corail, façonné à la main dans les ateliers historiques de l'île Saint-Louis.", description_en:"18-carat gold necklace set with coral beads, handcrafted in the historic workshops of Saint-Louis island.", features_fr:'["Or 18 carats","Perles de corail naturel","Façonné à la main","Pièce unique numérotée"]', features_en:'["18-carat gold","Natural coral beads","Handcrafted","Numbered unique piece"]', images:'["https://images.unsplash.com/photo-1573408301185-9519f94815b1?w=600&q=80","https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&q=80"]', dimensions:'', weight:'0.045kg', stock:5, rating:5.0, review_count:18, tags:'["bijou","or","saint-louis","collier","toucouleur"]', badge_fr:'Pièce Unique', badge_en:'Unique Piece', featured:1, is_new:0, region_fr:'Saint-Louis', region_en:'Saint-Louis' },
  { id:'2', slug:'bracelet-argent-tresse', name_fr:'Bracelet en Argent Tressé', name_en:'Braided Silver Bracelet', category:'artisanat', producer:'atelier-toure', price:18500, original_price:22000, description_fr:"Bracelet en argent massif tressé selon la technique ancestrale des forgerons lébous de Dakar. Gravures de motifs géométriques wolofs.", description_en:"Braided solid silver bracelet crafted using the ancestral technique of Lebou blacksmiths from Dakar. Engraved with Wolof geometric patterns.", features_fr:'["Argent 925","Tressage ancestral","Motifs wolofs","Ajustable"]', features_en:'["925 silver","Ancestral braiding","Wolof patterns","Adjustable"]', images:'["https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&q=80"]', dimensions:'', weight:'0.06kg', stock:12, rating:4.8, review_count:34, tags:'["bracelet","argent","bijou","artisanat"]', badge_fr:null, badge_en:null, featured:0, is_new:1, region_fr:'Saint-Louis', region_en:'Saint-Louis' },
  { id:'3', slug:'sculpture-bois-casamance', name_fr:'Sculpture Bois de Casamance', name_en:'Casamance Wood Sculpture', category:'artisanat', producer:'maison-fall', price:38000, original_price:null, description_fr:"Sculpture animalière en bois de fromager de Casamance, sculptée à la main par les artisans diolas de Ziguinchor.", description_en:"Animal sculpture in Casamance kapok wood, hand-carved by Diola artisans from Ziguinchor.", features_fr:'["Bois de fromager","Sculpté à la main","Finition huile de palme","Signé"]', features_en:'["Kapok wood","Hand-carved","Palm oil finish","Signed"]', images:'["https://images.unsplash.com/photo-1596552747891-0e7a8e3dada0?w=600&q=80"]', dimensions:'35cm × 15cm', weight:'1.1kg', stock:7, rating:4.9, review_count:22, tags:'["sculpture","bois","casamance","diola","lion"]', badge_fr:'Édition Limitée', badge_en:'Limited Edition', featured:1, is_new:0, region_fr:'Casamance', region_en:'Casamance' },
  { id:'4', slug:'panier-tresse-sine-saloum', name_fr:'Panier Tressé Sine-Saloum', name_en:'Sine-Saloum Woven Basket', category:'artisanat', producer:'atelier-toure', price:9500, original_price:12000, description_fr:"Grand panier tressé à la main en fibre de roseau du Sine-Saloum. Teintures naturelles à base de plantes locales.", description_en:"Large hand-woven basket in reed fiber from the Sine-Saloum. Natural plant-based dyes.", features_fr:'["Roseau naturel","Teinture végétale","Technique sérère","Multifonction"]', features_en:'["Natural reed","Vegetable dye","Serer technique","Multipurpose"]', images:'["https://images.unsplash.com/photo-1584589167171-541ce45f1eea?w=600&q=80"]', dimensions:'50cm × 40cm', weight:'0.6kg', stock:18, rating:4.6, review_count:41, tags:'["panier","roseau","sérère","sine-saloum"]', badge_fr:'Éco', badge_en:'Eco', featured:0, is_new:0, region_fr:'Sine-Saloum', region_en:'Sine-Saloum' },
  { id:'5', slug:'bissap-seche-premium', name_fr:'Bissap Séché Premium', name_en:'Premium Dried Bissap', category:'alimentation', producer:'ferme-ndiaye', price:4500, original_price:null, description_fr:"Fleurs d'hibiscus (bissap) séchées naturellement sans additifs. Cultivées en agriculture biologique dans la région de Thiès.", description_en:"Naturally dried hibiscus (bissap) flowers with no additives. Organically grown in the Thiès region.", features_fr:'["Bio certifié","Séchage naturel","Sans additifs","200g"]', features_en:'["Certified organic","Natural drying","No additives","200g"]', images:'["https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80"]', dimensions:'', weight:'200g', stock:60, rating:4.9, review_count:93, tags:'["bissap","hibiscus","infusion","biologique"]', badge_fr:'Bio', badge_en:'Organic', featured:1, is_new:0, region_fr:'Thiès', region_en:'Thiès' },
  { id:'6', slug:'coffret-epices-senegalaises', name_fr:'Coffret Épices Sénégalaises', name_en:'Senegalese Spice Gift Box', category:'alimentation', producer:'ferme-ndiaye', price:16500, original_price:20000, description_fr:"Coffret de 6 épices emblématiques du Sénégal : poivre de Selim, piment doux de Casamance, gingembre de Thiès, curcuma, ail déshydraté.", description_en:"Gift box of 6 iconic Senegalese spices: Selim pepper, sweet Casamance chili, Thiès ginger, turmeric, dehydrated garlic.", features_fr:'["6 épices","Séchage naturel","Sans conservateurs","Bocaux réutilisables"]', features_en:'["6 spices","Natural drying","No preservatives","Reusable jars"]', images:'["https://images.unsplash.com/photo-1506084868230-bb9d95c24759?w=600&q=80"]', dimensions:'', weight:'300g total', stock:22, rating:4.7, review_count:58, tags:'["épices","coffret","thiéboudienne","yassa","cadeau"]', badge_fr:'Idée Cadeau', badge_en:'Gift Idea', featured:1, is_new:1, region_fr:'Thiès / Casamance', region_en:'Thiès / Casamance' },
  { id:'7', slug:'poudre-bouye-baobab', name_fr:'Poudre de Bouye (Baobab)', name_en:'Bouye (Baobab) Powder', category:'alimentation', producer:'ferme-ndiaye', price:5800, original_price:null, description_fr:"Poudre de fruit de baobab (bouye) 100% naturelle, récoltée à la main dans les forêts du Sénégal.", description_en:"100% natural baobab fruit (bouye) powder, hand-harvested from Senegalese forests.", features_fr:'["100% naturel","Riche en vitamine C","Sans sucre ajouté","250g"]', features_en:'["100% natural","Rich in vitamin C","No added sugar","250g"]', images:'["https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&q=80"]', dimensions:'', weight:'250g', stock:45, rating:4.8, review_count:67, tags:'["bouye","baobab","superfood","vitamine c"]', badge_fr:'Superfood', badge_en:'Superfood', featured:0, is_new:0, region_fr:'Fatick', region_en:'Fatick' },
  { id:'8', slug:'sel-saint-louis-fume', name_fr:'Sel de Saint-Louis Fumé', name_en:'Smoked Saint-Louis Salt', category:'alimentation', producer:'ferme-ndiaye', price:3200, original_price:null, description_fr:"Sel marin récolté dans les salines de Saint-Louis, légèrement fumé au bois de palétuviers.", description_en:"Sea salt harvested from Saint-Louis salt pans, lightly smoked over mangrove wood.", features_fr:'["Sel marin naturel","Fumé au palétuvier","Sans additifs","Pot en terre cuite"]', features_en:'["Natural sea salt","Mangrove-smoked","No additives","Terracotta pot"]', images:'["https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&q=80"]', dimensions:'', weight:'150g', stock:38, rating:4.7, review_count:44, tags:'["sel","saint-louis","fumé","épice","artisanal"]', badge_fr:null, badge_en:null, featured:0, is_new:1, region_fr:'Saint-Louis', region_en:'Saint-Louis' },
  { id:'9', slug:'tissu-wax-imprime-6-yards', name_fr:'Tissu Wax Imprimé 6 Yards', name_en:'Printed Wax Fabric 6 Yards', category:'textile', producer:'tissage-diop', price:32000, original_price:null, description_fr:"Tissu wax authentique imprimé à motifs géométriques africains, tissé sur métiers traditionnels à Kaolack.", description_en:"Authentic wax fabric printed with African geometric patterns, woven on traditional looms in Kaolack.", features_fr:'["Coton 100% local","Motifs géométriques","Colorants naturels","6 yards"]', features_en:'["100% local cotton","Geometric patterns","Natural dyes","6 yards"]', images:'["https://images.unsplash.com/photo-1558171813-1e46e59b765b?w=600&q=80"]', dimensions:'5.5m × 1.20m', weight:'0.8kg', stock:14, rating:4.8, review_count:53, tags:'["wax","tissu","boubou","coton","africain"]', badge_fr:'Authentique', badge_en:'Authentic', featured:1, is_new:0, region_fr:'Kaolack', region_en:'Kaolack' },
  { id:'10', slug:'boubou-brode-homme', name_fr:'Boubou Brodé Homme', name_en:"Embroidered Men's Boubou", category:'textile', producer:'tissage-diop', price:55000, original_price:68000, description_fr:"Grand boubou 3 pièces en bazin riche brodé à la main, taille unique ajustable. Broderie dorée réalisée à Dakar.", description_en:"Grand 3-piece boubou in hand-embroidered bazin riche, adjustable one size. Gold embroidery made in Dakar.", features_fr:'["Bazin riche","Broderie or","3 pièces","Taille ajustable"]', features_en:'["Bazin riche","Gold embroidery","3 pieces","Adjustable size"]', images:'["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80"]', dimensions:'', weight:'0.9kg', stock:8, rating:4.9, review_count:29, tags:'["boubou","bazin","broderie","cérémonie","homme"]', badge_fr:'Cérémonie', badge_en:'Ceremony', featured:0, is_new:0, region_fr:'Kaolack / Dakar', region_en:'Kaolack / Dakar' },
  { id:'11', slug:'echarpe-soie-ndokett', name_fr:'Écharpe en Soie de Ndokett', name_en:'Ndokett Silk Scarf', category:'textile', producer:'tissage-diop', price:14500, original_price:null, description_fr:"Écharpe légère en tissu ndokett (soie artificielle sénégalaise) aux couleurs chatoyantes. Teinte à l'indigo naturel.", description_en:"Light scarf in ndokett fabric (Senegalese synthetic silk) in shimmering colors. Dyed with natural indigo.", features_fr:'["Tissu ndokett","Teinture indigo","Légère & douce","180cm × 60cm"]', features_en:'["Ndokett fabric","Indigo dye","Light & soft","180cm × 60cm"]', images:'["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80"]', dimensions:'180cm × 60cm', weight:'0.12kg', stock:20, rating:4.6, review_count:17, tags:'["écharpe","ndokett","indigo","soie","accessoire"]', badge_fr:'Nouveau', badge_en:'New', featured:0, is_new:1, region_fr:'Kaolack', region_en:'Kaolack' },
  { id:'12', slug:'beurre-karite-casamance', name_fr:'Beurre de Karité Casamance', name_en:'Casamance Shea Butter', category:'cosmetiques', producer:'naturelle-sow', price:7500, original_price:null, description_fr:"Beurre de karité non raffiné récolté dans les forêts sacrées de Casamance. Extraction à froid par les femmes diolas.", description_en:"Unrefined shea butter harvested from the sacred forests of Casamance. Cold-extracted by Diola women.", features_fr:'["Non raffiné","Extraction à froid","Vitamines A, E, F","200ml"]', features_en:'["Unrefined","Cold-extracted","Vitamins A, E, F","200ml"]', images:'["https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80"]', dimensions:'', weight:'200g', stock:70, rating:4.9, review_count:157, tags:'["karité","hydratation","casamance","corps","naturel"]', badge_fr:'Best-seller', badge_en:'Best Seller', featured:1, is_new:0, region_fr:'Casamance', region_en:'Casamance' },
  { id:'13', slug:'huile-coco-casamance', name_fr:'Huile de Coco de Casamance', name_en:'Casamance Coconut Oil', category:'cosmetiques', producer:'naturelle-sow', price:8900, original_price:null, description_fr:"Huile de coco vierge extra pressée à froid, issue des cocotiers de Casamance. Multi-usage : corps, démaquillant, cheveux.", description_en:"Extra virgin coconut oil cold-pressed from Casamance coconut trees. Multi-purpose: body, makeup remover, hair.", features_fr:'["Vierge extra","Pressée à froid","Multi-usage","100ml verre recyclé"]', features_en:'["Extra virgin","Cold-pressed","Multi-purpose","100ml recycled glass"]', images:'["https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=600&q=80"]', dimensions:'', weight:'100ml', stock:40, rating:4.8, review_count:88, tags:'["coco","huile","casamance","cheveux","corps"]', badge_fr:null, badge_en:null, featured:0, is_new:0, region_fr:'Casamance', region_en:'Casamance' },
  { id:'14', slug:'savon-karite-baobab', name_fr:'Savon au Lait de Karité & Baobab', name_en:'Shea Milk & Baobab Soap', category:'cosmetiques', producer:'naturelle-sow', price:2800, original_price:null, description_fr:"Savon artisanal formulé au lait de karité de Casamance et à l'huile de baobab. Surgras à 8%, peaux sensibles.", description_en:"Artisanal soap with Casamance shea milk and baobab oil. 8% superfatted, sensitive skin.", features_fr:'["Lait de karité","Huile de baobab","Surgras 8%","100g"]', features_en:'["Shea milk","Baobab oil","8% superfatted","100g"]', images:'["https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600&q=80"]', dimensions:'', weight:'100g', stock:90, rating:4.7, review_count:112, tags:'["savon","karité","baobab","peau sensible","artisanal"]', badge_fr:'Vegan', badge_en:'Vegan', featured:0, is_new:0, region_fr:'Ziguinchor', region_en:'Ziguinchor' },
  { id:'15', slug:'gommage-sel-saint-louis-coco', name_fr:'Gommage au Sel de Saint-Louis & Coco', name_en:'Saint-Louis Salt & Coconut Scrub', category:'cosmetiques', producer:'naturelle-sow', price:9500, original_price:11500, description_fr:"Gommage corps exfoliant au sel marin de Saint-Louis et à l'huile de coco de Casamance.", description_en:"Exfoliating body scrub with Saint-Louis sea salt and Casamance coconut oil.", features_fr:'["Sel de Saint-Louis","Huile de coco","Anti-taches","200g"]', features_en:'["Saint-Louis salt","Coconut oil","Anti-blemish","200g"]', images:'["https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=600&q=80"]', dimensions:'', weight:'200g', stock:35, rating:4.6, review_count:49, tags:'["gommage","sel","coco","corps","exfoliant"]', badge_fr:null, badge_en:null, featured:0, is_new:1, region_fr:'Saint-Louis / Casamance', region_en:'Saint-Louis / Casamance' },
  { id:'16', slug:'peinture-sous-verre-souwere', name_fr:'Peinture sous Verre Souwère', name_en:'Souwère Reverse Glass Painting', category:'decoration', producer:'maison-fall', price:42000, original_price:null, description_fr:"Peinture sous verre (souwère) originale signée Cheikh Fall, représentant une scène de marché dakarois aux couleurs vives.", description_en:"Original reverse glass painting (souwère) signed by Cheikh Fall, depicting a vibrant Dakar market scene.", features_fr:'["Souwère original","Signé & numéroté","Cadre inclus","40cm × 50cm"]', features_en:'["Original souwère","Signed & numbered","Frame included","40cm × 50cm"]', images:'["https://images.unsplash.com/photo-1561839561-b13bcfe95249?w=600&q=80"]', dimensions:'40cm × 50cm', weight:'0.9kg', stock:4, rating:5.0, review_count:21, tags:'["souwère","peinture","dakar","art","verre"]', badge_fr:'Œuvre Originale', badge_en:'Original Artwork', featured:1, is_new:0, region_fr:'Dakar', region_en:'Dakar' },
  { id:'17', slug:'tableau-sable-dakar', name_fr:'Tableau de Sable de Dakar', name_en:'Dakar Sand Painting', category:'decoration', producer:'maison-fall', price:18500, original_price:null, description_fr:"Tableau réalisé avec les sables multicolores naturels des plages et déserts du Sénégal. Représentation abstraite de la Teranga.", description_en:"Painting made with natural multicolored sands from Senegalese beaches and deserts. Abstract Teranga representation.", features_fr:'["Sable naturel","Technique unique","Cadre bois","30cm × 40cm"]', features_en:'["Natural sand","Unique technique","Wood frame","30cm × 40cm"]', images:'["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80"]', dimensions:'30cm × 40cm', weight:'0.7kg', stock:9, rating:4.8, review_count:15, tags:'["sable","tableau","dakar","teranga","art"]', badge_fr:null, badge_en:null, featured:0, is_new:0, region_fr:'Dakar', region_en:'Dakar' },
  { id:'18', slug:'coussin-wax-serti-or', name_fr:'Coussin en Wax Serti Or', name_en:'Gold-Trim Wax Cushion', category:'decoration', producer:'tissage-diop', price:13500, original_price:16000, description_fr:"Coussin décoratif recouvert d'un wax aux motifs africains avec passepoil doré cousu à la main.", description_en:"Decorative cushion covered in African wax patterns with hand-sewn gold piping.", features_fr:'["Tissu wax","Passepoil or","Kapok de Casamance","45cm × 45cm"]', features_en:'["Wax fabric","Gold piping","Casamance kapok","45cm × 45cm"]', images:'["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80"]', dimensions:'45cm × 45cm', weight:'0.4kg', stock:16, rating:4.7, review_count:28, tags:'["coussin","wax","décoration","salon"]', badge_fr:null, badge_en:null, featured:0, is_new:0, region_fr:'Kaolack', region_en:'Kaolack' },
  { id:'19', slug:'bougie-thiouraye-vanille', name_fr:'Bougie Thiouraye & Vanille', name_en:'Thiouraye & Vanilla Candle', category:'decoration', producer:'naturelle-sow', price:6500, original_price:null, description_fr:"Bougie artisanale à la cire de karité parfumée au thiouraye (encens sénégalais) et à la vanille. 40h de combustion.", description_en:"Artisanal shea butter candle scented with thiouraye (Senegalese incense) and vanilla. 40h burn time.", features_fr:'["Cire de karité","Thiouraye & Vanille","40h combustion","Céramique locale"]', features_en:'["Shea wax","Thiouraye & Vanilla","40h burn","Local ceramic"]', images:'["https://images.unsplash.com/photo-1616401784845-180882ba9ba8?w=600&q=80"]', dimensions:'', weight:'200g', stock:32, rating:4.8, review_count:46, tags:'["bougie","thiouraye","encens","sénégal","ambiance"]', badge_fr:'Éco', badge_en:'Eco', featured:0, is_new:1, region_fr:'Ziguinchor', region_en:'Ziguinchor' },
  { id:'20', slug:'coffret-teranga-senegal', name_fr:'Coffret Teranga — Le Sénégal en Box', name_en:'Teranga Box — Senegal in a Box', category:'alimentation', producer:'ferme-ndiaye', price:42000, original_price:52000, description_fr:"Notre coffret signature : 9 produits emblématiques du Sénégal sélectionnés chez nos meilleurs producteurs.", description_en:"Our signature gift box: 9 iconic Senegalese products selected from our best producers.", features_fr:'["9 produits","5 producteurs","Emballage cadeau","Carte personnalisée"]', features_en:'["9 products","5 producers","Gift packaging","Personalized card"]', images:'["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80"]', dimensions:'', weight:'3kg', stock:18, rating:5.0, review_count:62, tags:'["coffret","teranga","sénégal","cadeau","best-of"]', badge_fr:'⭐ Exclusif', badge_en:'⭐ Exclusive', featured:1, is_new:0, region_fr:'Tout le Sénégal', region_en:'All of Senegal' },
  { id:'21', slug:'tam-tam-sabar-decoratif', name_fr:'Tam-Tam Sabar Décoratif', name_en:'Decorative Sabar Drum', category:'artisanat', producer:'maison-fall', price:28500, original_price:null, description_fr:"Sabar (tam-tam sénégalais) miniature sculpté en bois de dimb et recouvert de peau de chèvre tannée naturellement.", description_en:"Miniature sabar (Senegalese drum) carved in dimb wood and covered with naturally tanned goatskin.", features_fr:'["Bois de dimb","Peau de chèvre","Jouable","30cm de hauteur"]', features_en:'["Dimb wood","Goatskin","Playable","30cm height"]', images:'["https://images.unsplash.com/photo-1584589167171-541ce45f1eea?w=600&q=80"]', dimensions:'30cm × 15cm', weight:'0.9kg', stock:10, rating:4.7, review_count:19, tags:'["sabar","tam-tam","mbalax","instrument","décoration"]', badge_fr:null, badge_en:null, featured:0, is_new:1, region_fr:'Dakar', region_en:'Dakar' },
  { id:'22', slug:'nappe-bazin-brode', name_fr:'Nappe en Bazin Brodé', name_en:'Embroidered Bazin Tablecloth', category:'textile', producer:'tissage-diop', price:24500, original_price:null, description_fr:"Nappe rectangulaire en bazin blanc brodé à la main de fils dorés, motifs floraux d'inspiration sénégalaise.", description_en:"Rectangular tablecloth in white bazin hand-embroidered with gold threads, Senegalese-inspired floral patterns.", features_fr:'["Bazin blanc","Broderie fil or","Bords frangés","150cm × 250cm"]', features_en:'["White bazin","Gold thread embroidery","Fringed edges","150cm × 250cm"]', images:'["https://images.unsplash.com/photo-1558171813-1e46e59b765b?w=600&q=80"]', dimensions:'150cm × 250cm', weight:'0.9kg', stock:10, rating:4.6, review_count:13, tags:'["nappe","bazin","broderie","cérémonie","table"]', badge_fr:null, badge_en:null, featured:0, is_new:0, region_fr:'Kaolack', region_en:'Kaolack' },
]

async function seed() {
  const conn = await pool.getConnection()
  try {
    for (const p of products) {
      await conn.execute(
        `INSERT IGNORE INTO products
          (product_id,slug,name_fr,name_en,category,producer,price,original_price,
           description_fr,description_en,features_fr,features_en,images,dimensions,weight,
           stock,rating,review_count,tags,badge_fr,badge_en,featured,is_new,region_fr,region_en)
         VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
        [p.id,p.slug,p.name_fr,p.name_en,p.category,p.producer,p.price,p.original_price,
         p.description_fr,p.description_en,p.features_fr,p.features_en,p.images,p.dimensions,p.weight,
         p.stock,p.rating,p.review_count,p.tags,p.badge_fr,p.badge_en,p.featured,p.is_new,p.region_fr,p.region_en]
      )
    }
    console.log(`✅ ${products.length} produits insérés dans senbitik_db.products`)
  } finally {
    conn.release()
    process.exit(0)
  }
}

seed().catch(err => { console.error('Erreur seed:', err); process.exit(1) })
