import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext(null)

export const translations = {
  fr: {
    nav: {
      home: 'Accueil',
      shop: 'Boutique',
      producers: 'Producteurs',
      about: 'À Propos',
      contact: 'Contact',
      login: 'Connexion',
      register: "S'inscrire",
      profile: 'Mon Profil',
      orders: 'Mes Commandes',
      wishlist: 'Favoris',
      logout: 'Déconnexion',
      cart: 'Panier',
    },
    hero: {
      badge: 'Produits 100% Sénégalais',
      title: 'Le meilleur du',
      titleHighlight: 'terroir sénégalais',
      subtitle: 'Découvrez des produits authentiques directement auprès de nos artisans et producteurs sénégalais. Artisanat de Saint-Louis, épices de Thiès, cosmétiques de Casamance — achetez sénégalais, soutenez le local.',
      cta: 'Explorer la boutique',
      ctaSecondary: 'Nos artisans',
      stat1: 'Artisans',
      stat2: 'Produits',
      stat3: 'Clients satisfaits',
      stat4: 'Régions',
    },
    sections: {
      featuredProducts: 'Produits en Vedette',
      featuredSubtitle: 'Une sélection soigneuse des meilleurs produits de nos artisans sénégalais',
      categories: 'Nos Catégories',
      categoriesSubtitle: 'Artisanat, alimentation, textile, cosmétiques — tout le génie sénégalais',
      producers: 'Nos Producteurs',
      producersSubtitle: 'Des femmes et des hommes de chez nous qui perpétuent des savoir-faire ancestraux',
      testimonials: 'Ce que disent nos clients',
      testimonialsSubtitle: 'Des milliers de Sénégalais satisfaits, au pays et dans la diaspora',
      newsletter: 'Restez informé',
      newsletterSubtitle: "Inscrivez-vous et recevez nos offres exclusives, nouveautés et histoires de producteurs sénégalais.",
      newArrivals: 'Nouveautés',
    },
    product: {
      addToCart: 'Ajouter au panier',
      addedToCart: 'Ajouté au panier !',
      addToWishlist: 'Ajouter aux favoris',
      removeFromWishlist: 'Retirer des favoris',
      outOfStock: 'Rupture de stock',
      quantity: 'Quantité',
      inStock: 'En stock',
      reviews: 'avis',
      seeDetails: 'Voir les détails',
      similarProducts: 'Produits similaires',
      producerOf: 'Producteur',
      characteristics: 'Caractéristiques',
      description: 'Description',
      buyNow: 'Acheter maintenant',
    },
    cart: {
      title: 'Mon Panier',
      empty: 'Votre panier est vide',
      emptySubtitle: 'Découvrez nos produits et ajoutez-en au panier',
      continueShopping: 'Continuer mes achats',
      subtotal: 'Sous-total',
      shipping: 'Livraison',
      shippingFree: 'Gratuite',
      shippingEstimate: 'Estimée à la livraison',
      total: 'Total',
      checkout: 'Passer commande',
      remove: 'Supprimer',
      items: 'articles',
      promoCode: 'Code promo',
      apply: 'Appliquer',
    },
    auth: {
      login: 'Connexion',
      register: 'Créer un compte',
      email: 'Email',
      password: 'Mot de passe',
      confirmPassword: 'Confirmer le mot de passe',
      firstName: 'Prénom',
      lastName: 'Nom',
      forgotPassword: 'Mot de passe oublié ?',
      noAccount: "Vous n'avez pas de compte ?",
      hasAccount: 'Déjà un compte ?',
      loginSuccess: 'Connexion réussie !',
      registerSuccess: 'Compte créé avec succès !',
      logoutSuccess: 'Déconnexion réussie',
    },
    footer: {
      slogan: 'Le terroir à portée de clic',
      shop: 'Boutique',
      allProducts: 'Tous les produits',
      newArrivals: 'Nouveautés',
      bestSellers: 'Meilleures ventes',
      info: 'Informations',
      about: 'À Propos',
      contact: 'Contact',
      faq: 'FAQ',
      legal: 'Mentions Légales',
      cgv: 'CGV',
      followUs: 'Suivez-nous',
      rights: 'Tous droits réservés',
      madeWith: 'Fait avec',
      forTerroir: 'pour le Sénégal',
      newsletter: {
        title: 'Newsletter',
        placeholder: 'Votre email',
        button: "S'inscrire",
        success: 'Merci pour votre inscription !',
      },
    },
    common: {
      loading: 'Chargement...',
      error: 'Une erreur est survenue',
      retry: 'Réessayer',
      seeAll: 'Voir tout',
      learnMore: 'En savoir plus',
      close: 'Fermer',
      cancel: 'Annuler',
      confirm: 'Confirmer',
      save: 'Sauvegarder',
      edit: 'Modifier',
      delete: 'Supprimer',
      search: 'Rechercher',
      filter: 'Filtrer',
      sort: 'Trier',
      price: 'Prix',
      category: 'Catégorie',
      region: 'Région',
      rating: 'Note',
      noResults: 'Aucun résultat trouvé',
      backToShop: 'Retour à la boutique',
    },
  },
  en: {
    nav: {
      home: 'Home',
      shop: 'Shop',
      producers: 'Producers',
      about: 'About',
      contact: 'Contact',
      login: 'Log In',
      register: 'Sign Up',
      profile: 'My Profile',
      orders: 'My Orders',
      wishlist: 'Wishlist',
      logout: 'Log Out',
      cart: 'Cart',
    },
    hero: {
      badge: '100% Senegalese Products',
      title: 'The best of',
      titleHighlight: 'Senegalese terroir',
      subtitle: 'Discover authentic products directly from Senegalese artisans and producers. Saint-Louis crafts, Thiès spices, Casamance cosmetics — buy Senegalese, support local.',
      cta: 'Explore the shop',
      ctaSecondary: 'Our artisans',
      stat1: 'Artisans',
      stat2: 'Products',
      stat3: 'Happy customers',
      stat4: 'Regions',
    },
    sections: {
      featuredProducts: 'Featured Products',
      featuredSubtitle: 'A careful selection of the best products from our Senegalese artisans',
      categories: 'Our Categories',
      categoriesSubtitle: 'Crafts, food, textiles, cosmetics — all the Senegalese genius',
      producers: 'Our Producers',
      producersSubtitle: 'Men and women from here who perpetuate ancestral knowledge',
      testimonials: 'What our customers say',
      testimonialsSubtitle: 'Thousands of satisfied Senegalese customers, at home and in the diaspora',
      newsletter: 'Stay informed',
      newsletterSubtitle: 'Subscribe and receive our exclusive offers, news and Senegalese producer stories.',
      newArrivals: 'New Arrivals',
    },
    product: {
      addToCart: 'Add to cart',
      addedToCart: 'Added to cart!',
      addToWishlist: 'Add to wishlist',
      removeFromWishlist: 'Remove from wishlist',
      outOfStock: 'Out of stock',
      quantity: 'Quantity',
      inStock: 'In stock',
      reviews: 'reviews',
      seeDetails: 'See details',
      similarProducts: 'Similar products',
      producerOf: 'Producer',
      characteristics: 'Characteristics',
      description: 'Description',
      buyNow: 'Buy now',
    },
    cart: {
      title: 'My Cart',
      empty: 'Your cart is empty',
      emptySubtitle: 'Discover our products and add them to your cart',
      continueShopping: 'Continue shopping',
      subtotal: 'Subtotal',
      shipping: 'Shipping',
      shippingFree: 'Free',
      shippingEstimate: 'Estimated at delivery',
      total: 'Total',
      checkout: 'Checkout',
      remove: 'Remove',
      items: 'items',
      promoCode: 'Promo code',
      apply: 'Apply',
    },
    auth: {
      login: 'Log In',
      register: 'Create account',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm password',
      firstName: 'First name',
      lastName: 'Last name',
      forgotPassword: 'Forgot password?',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account?',
      loginSuccess: 'Successfully logged in!',
      registerSuccess: 'Account created successfully!',
      logoutSuccess: 'Successfully logged out',
    },
    footer: {
      slogan: 'The terroir at your fingertips',
      shop: 'Shop',
      allProducts: 'All products',
      newArrivals: 'New arrivals',
      bestSellers: 'Best sellers',
      info: 'Information',
      about: 'About',
      contact: 'Contact',
      faq: 'FAQ',
      legal: 'Legal Notice',
      cgv: 'Terms',
      followUs: 'Follow us',
      rights: 'All rights reserved',
      madeWith: 'Made with',
      forTerroir: 'for Senegal',
      newsletter: {
        title: 'Newsletter',
        placeholder: 'Your email',
        button: 'Subscribe',
        success: 'Thank you for subscribing!',
      },
    },
    common: {
      loading: 'Loading...',
      error: 'An error occurred',
      retry: 'Retry',
      seeAll: 'See all',
      learnMore: 'Learn more',
      close: 'Close',
      cancel: 'Cancel',
      confirm: 'Confirm',
      save: 'Save',
      edit: 'Edit',
      delete: 'Delete',
      search: 'Search',
      filter: 'Filter',
      sort: 'Sort',
      price: 'Price',
      category: 'Category',
      region: 'Region',
      rating: 'Rating',
      noResults: 'No results found',
      backToShop: 'Back to shop',
    },
  },
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() =>
    localStorage.getItem('senbitik-lang') || 'fr'
  )

  const switchLang = (newLang) => {
    setLang(newLang)
    localStorage.setItem('senbitik-lang', newLang)
  }

  const t = translations[lang] || translations.fr

  const getText = (obj) => {
    if (!obj) return ''
    if (typeof obj === 'string') return obj
    return obj[lang] || obj.fr || ''
  }

  return (
    <LanguageContext.Provider value={{ lang, switchLang, t, getText }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}
